### ISSUE TITLE
Import error in check_imported_dlls.py

### ISSUE THREAD

**Issue by lapluma** [deptofdefense/SalSA#9]
I'm trying to run this tools on Mac OSX.  I did:

```
git clone https://github.com/deptofdefense/SalSA
cd SalSA
python main.py -f ~/crypt32.dll
```
And I got the following error:
```MacBook-Pro:SalSA $ python main.py -f ~/crypt32.dll 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    __import__('rules.' + r)
  File "/SalSA/rules/check_imported_dlls.py", line 8, in <module>
    import ordinal_mappings
ModuleNotFoundError: No module named 'ordinal_mappings'```

Any help would be appreciated!

**Comment by georgeprichici** [comment]
Should use full path: 
`import rules.ordinal_mappings as ordinal_mappings`

Also, make sure you use python2 when you are trying it out

**Comment by a-rey** [comment]
Fixed here https://github.com/deptofdefense/SalSA/commit/0b8560d018f60e3d79c9e782d5e9afa1816596b8. Use Python3 now
